
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1207025
	#The name of the modpack
	modpackName = "The Fungal Infection"
	#The version of the modpack
	modpackVersion = "v1.4.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

